#!/usr/bin/env nbb
(ns gen-commands
  "Write the CLI command registry from the routes `server.clj` actually serves.

  The scanning is `cloud.itonami.app.route-scan`, a portable `.cljc` this shares
  with `commands-test` — written twice, the generator and its gate would
  eventually disagree, and the disagreement would read as drift in the routes
  rather than in the two scanners.

  What is here is the part that is not portable: reading one file and writing
  another.

    nbb --classpath src dev/gen_commands.cljs           # write the registry
    nbb --classpath src dev/gen_commands.cljs --check   # exit 1 if it is stale
    nbb --classpath src dev/gen_commands.cljs --print   # print, write nothing"
  (:require ["fs" :as fs]
            [cloud.itonami.app.route-scan :as scan]))

(def server-file "src/cloud/itonami/app/server.clj")
(def resource-file "resources/cloud-itonami-app.commands.edn")

(defn- render [value]
  (str ";; Generated by dev/gen_commands.cljs from " server-file ".\n"
       ";; Do not edit: regenerate it, and commands-test fails when this file\n"
       ";; no longer matches the routes.\n"
       (pr-str value) "\n"))

(let [args (set (drop 3 (js->clj js/process.argv)))
      value (scan/registry (fs/readFileSync server-file "utf8") server-file)
      text (render value)
      {:keys [routes commands human-only unauthenticated]} (:counts value)]
  (cond
    (contains? args "--print")
    (println text)

    (contains? args "--check")
    (let [current (try (fs/readFileSync resource-file "utf8") (catch :default _ nil))]
      (if (= current text)
        (println "commands.edn is current:" commands "commands")
        (do (println "STALE:" resource-file "does not match" server-file
                     "-- run `nbb --classpath src dev/gen_commands.cljs`")
            (set! (.-exitCode js/process) 1))))

    :else
    (do (fs/writeFileSync resource-file text)
        (println "wrote" resource-file
                 (str "(" commands " commands from " routes " routes; "
                      human-only " human-passkey-only, "
                      unauthenticated " unauthenticated)")))))
