(ns cloud.itonami.app.test-runner
  "The suite is an explicit list, and an explicit list can be incomplete
  silently — a new `*_test.clj` that nobody adds here does not fail, it simply
  never runs, and the build stays green while the tests in it never execute.
  (Measured: `storj_test.clj` was added and the count did not move.) So the
  list stays explicit, and `-main` refuses to run a suite that does not cover
  every test file on the path."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :as test]
            [cloud.itonami.app.authority-test]
            [cloud.itonami.app.business-test]
            [cloud.itonami.app.agent-session-test]
            [cloud.itonami.app.a2a-test]
            [cloud.itonami.app.kaiyu-local-test]
            [cloud.itonami.app.launcher-test]
            [cloud.itonami.app.business-http-test]
            [cloud.itonami.app.canvas-test]
            [cloud.itonami.app.capture-test]
            [cloud.itonami.app.capture-http-test]
            [cloud.itonami.app.card-statement-test]
            [cloud.itonami.app.cli-test]
            [cloud.itonami.app.west-kotoba-refactor-test]
            [cloud.itonami.app.commands-test]
            [cloud.itonami.app.connectors-test]
            [cloud.itonami.app.desktop-test]
            [cloud.itonami.app.device-test]
            [cloud.itonami.app.decision-method-test]
            [cloud.itonami.app.disk-space-test]
            [cloud.itonami.app.appearance-test]
            [cloud.itonami.app.hokusai-test]
            [cloud.itonami.app.media-tools-test]
            [cloud.itonami.app.git-hygiene-test]
            [cloud.itonami.app.domain-tools-test]
            [cloud.itonami.app.bot-import-test]
            [cloud.itonami.app.bot-test]
            [cloud.itonami.app.bot-slo-test]
            [cloud.itonami.app.bot-authority-test]
            [cloud.itonami.app.bot-dispatcher-test]
            [cloud.itonami.app.bot-identity-test]
            [cloud.itonami.app.bots-test]
            [cloud.itonami.app.virtual-shell-test]
            [cloud.itonami.app.host-grant-test]
            [cloud.itonami.app.host-store-bound-test]
            [cloud.itonami.app.store-journal-test]
            [cloud.itonami.app.store :as store]
            [cloud.itonami.app.loops-test]
            [cloud.itonami.app.lawfirm-test]
            [cloud.itonami.app.kotobase-federation-test]
            [cloud.itonami.app.local-query-test]
            [cloud.itonami.app.fax-test]
            [cloud.itonami.app.tenant-capability-test]
            [cloud.itonami.app.freebusy-test]
            [cloud.itonami.app.metrics-test]
            [cloud.itonami.app.portfolio-test]
            [cloud.itonami.app.policy-kotoba-parity-test]
            [cloud.itonami.app.native-canary-test]
            [cloud.itonami.app.health-kotoba-parity-test]
            [cloud.itonami.app.workforce-cadence-kotoba-parity-test]
            [cloud.itonami.app.health-http-test]
            [cloud.itonami.app.store-core-test]
            [cloud.itonami.app.store-core-kotoba-parity-test]
            [cloud.itonami.app.store-agreement-test]
            [cloud.itonami.app.central-auth-http-test]
            [cloud.itonami.app.oauth-resource-kotoba-parity-test]
            [cloud.itonami.app.oauth-resource-http-test]
            [cloud.itonami.app.did-web-kotoba-parity-test]
            [cloud.itonami.app.did-web-http-test]
            [cloud.itonami.app.trust-discovery-http-test]
            [cloud.itonami.app.humanity-trust-test]
            [cloud.itonami.app.humanity-trust-http-test]
            [cloud.itonami.app.human-work-test]
            [cloud.itonami.app.human-work-assurance-test]
            [cloud.itonami.app.human-work-http-test]
            [cloud.itonami.app.human-work-x402-test]
            [cloud.itonami.app.fleet-core-kotoba-parity-test]
            [cloud.itonami.app.organism-worker-kotoba-parity-test]
            ;; b17e0c6 added this and did not register it, so the runner's own
            ;; completeness check failed the suite and the test it added never
            ;; ran. That check is why we know; without it the new coverage
            ;; would simply have been absent and green.
            [cloud.itonami.app.kotoba-oracle-test]
            [cloud.itonami.app.oracle-cljs-parity-test]
            [cloud.itonami.app.work-transitions-kotoba-parity-test]
            [cloud.itonami.app.approval-kotoba-parity-test]
            [cloud.itonami.app.routine-kotoba-parity-test]
            [cloud.itonami.app.model-routing-kotoba-parity-test]
            [cloud.itonami.app.bot-turn-guards-test]
            [cloud.itonami.app.model-routing-http-test]
            [cloud.itonami.app.routines-test]
            [cloud.itonami.app.handoff-kotoba-parity-test]
            [cloud.itonami.app.peer-kotoba-parity-test]
            [cloud.itonami.app.session-handoff-kotoba-parity-test]
            [cloud.itonami.app.mail-age-key-test]
            [cloud.itonami.app.mail-authentication-test]
            [cloud.itonami.app.mail-origins-test]
            [cloud.itonami.app.mail-projects-test]
            [cloud.itonami.app.conversation-context-test]
            [cloud.itonami.app.project-repository-test]
            [cloud.itonami.app.project-remote-test]
            [cloud.itonami.app.project-transfer-test]
            [cloud.itonami.app.repos-test]
            [cloud.itonami.app.repository-storage-test]
            [cloud.itonami.app.repository-qualification-test]
            [cloud.itonami.app.repository-invariants-test]
            [cloud.itonami.app.repository-runtime-test]
            [cloud.itonami.app.repository-actor-test]
            [cloud.itonami.app.repository-profile-ci-test]
            [cloud.itonami.app.mailbox-test]
            [cloud.itonami.app.mailbox-http-test]
            [cloud.itonami.app.mail-sync-test]
            [cloud.itonami.app.mail-account-test]
            [cloud.itonami.app.mail-domain-authority-test]
            [cloud.itonami.app.mail-domain-records-test]
            [cloud.itonami.app.tls-binding-test]
            [cloud.itonami.app.tls-certificate-test]
            [cloud.itonami.app.mail-gmail-test]
            [cloud.itonami.app.mail-imap-test]
            [cloud.itonami.app.mail-pop3-test]
            [cloud.itonami.app.mail-send-test]
            [cloud.itonami.app.messenger-test]
            [cloud.itonami.app.messenger-http-test]
            [cloud.itonami.app.organism-messenger-transport-test]
            [cloud.itonami.app.signal-browser-test]
            [cloud.itonami.app.scheduler-test]
            [cloud.itonami.app.scheduler-http-test]
            [cloud.itonami.app.bulky-waste-test]
            [cloud.itonami.app.bulky-waste-http-test]
            [cloud.itonami.app.sites-test]
            [cloud.itonami.app.authority.adapters-test]
            [cloud.itonami.app.authority.api-test]
            [cloud.itonami.app.authority.number-test]
            [cloud.itonami.app.authority.payment-test]
            [cloud.itonami.app.authority.posture-test]
            [cloud.itonami.app.authority-http-test]
            [cloud.itonami.app.authority.transport-test]
            [cloud.itonami.app.config-test]
            [cloud.itonami.app.contracts-test]
            [cloud.itonami.app.chronicle-test]
            [cloud.itonami.app.core-test]
            [cloud.itonami.app.credential-http-test]
            [cloud.itonami.app.credential-rdf-test]
            [cloud.itonami.app.presentation-request-test]
            [cloud.itonami.app.credential-sd-jwt-test]
            [cloud.itonami.app.credential-test]
            [cloud.itonami.app.credential-trust-test]
            [cloud.itonami.app.data-isolation-test]
            [cloud.itonami.app.did-test]
            [cloud.itonami.app.acme-test]
            [cloud.itonami.app.binding-sweep-test]
            [cloud.itonami.app.domain-name-test]
            [cloud.itonami.app.domain-binding-kotoba-parity-test]
            [cloud.itonami.app.domain-verification-test]
            [cloud.itonami.app.domain-verification-http-test]
            [cloud.itonami.app.email-login-test]
            [cloud.itonami.app.config-policy-test]
            [cloud.itonami.app.host-bounds-test]
            [cloud.itonami.app.provider-retry-test]
            [cloud.itonami.app.identity-lifecycle-test]
            [cloud.itonami.app.issue-comment-test]
            [cloud.itonami.app.lifecycle-test]
            [cloud.itonami.app.issue-comment-http-test]
            [cloud.itonami.app.loopback-origin-test]
            [cloud.itonami.app.sso-login-test]
            [cloud.itonami.app.documents-test]
            [cloud.itonami.app.drive-crypto-test]
            [cloud.itonami.app.drive-delivery-test]
            [cloud.itonami.app.file-provider-test]
            [cloud.itonami.app.file-provider-http-test]
            [cloud.itonami.app.workspace-reachability-test]
            [cloud.itonami.app.workspace-tools-test]
            [cloud.itonami.app.web-script-test]
            [cloud.itonami.app.bundle-test]
            [cloud.itonami.app.kotobase-objects-test]
            [cloud.itonami.app.drive-store-migration-test]
            [cloud.itonami.app.drive-fs-test]
            [cloud.itonami.app.latest-test]
            [cloud.itonami.app.graph-test]
            [cloud.itonami.app.work-governance-test]
            [cloud.itonami.app.github-projects-writeback-test]
            [cloud.itonami.app.github-projects-source-test]
            [cloud.itonami.app.work-runtime-test]
            [cloud.itonami.app.work-partition-store-test]
            [cloud.itonami.app.work-approval-test]
            [cloud.itonami.app.work-organism-dispatch-test]
            [cloud.itonami.app.esign-test]
            [cloud.itonami.app.esign-retention-test]
            [cloud.itonami.app.filecoin-test]
            [cloud.itonami.app.fleet-test]
            [cloud.itonami.app.folder-sync-test]
            [cloud.itonami.app.gc-test]
            [cloud.itonami.app.operator-test]
            [cloud.itonami.app.funding-test]
            [cloud.itonami.app.mcp-test]
            [cloud.itonami.app.mcp-http-test]
            [cloud.itonami.app.namespaces-test]
            [cloud.itonami.app.fleet-tools-test]
            [cloud.itonami.app.openai-compat-test]
            [cloud.itonami.app.hermes-compat-test]
            [cloud.itonami.app.hermes-migration-test]
            [cloud.itonami.app.hermes-compat-http-test]
            [cloud.itonami.app.provider-test]
            [cloud.itonami.app.pageview-test]
            [cloud.itonami.app.passkey-test]
            [cloud.itonami.app.payment-settlement-actor-test]
            [cloud.itonami.app.payment-tools-test]
            [cloud.itonami.app.paypay-bank-test]
            [cloud.itonami.app.storj-node-test]
            [cloud.itonami.app.store-test]
            [cloud.itonami.app.storj-test]
            [cloud.itonami.app.tenant-connection-test]
            [cloud.itonami.app.tenant-connection-http-test]
            [cloud.itonami.app.tenant-repository-test]
            [cloud.itonami.app.updater-test]
            [cloud.itonami.app.oauth-resource-test]
            [cloud.itonami.app.org-root-did-test]
            [cloud.itonami.app.did-webvh-http-test]
            [cloud.itonami.app.oauth-did-binding-test]
            [cloud.itonami.app.worker-http-test]
            [cloud.itonami.app.wallet-test]
            [cloud.itonami.app.smart-account-owner-test]
            [cloud.itonami.app.wallet-http-test]
            [cloud.itonami.app.wallet-send-test]
            [cloud.itonami.app.commerce-test]
            [cloud.itonami.app.storefront-http-test]))

(def ^:private namespaces
  '[cloud.itonami.app.authority-test
    cloud.itonami.app.a2a-test
    cloud.itonami.app.business-test
    cloud.itonami.app.agent-session-test
    cloud.itonami.app.kaiyu-local-test
    cloud.itonami.app.launcher-test
    cloud.itonami.app.business-http-test
    cloud.itonami.app.canvas-test
    cloud.itonami.app.capture-test
    cloud.itonami.app.capture-http-test
    cloud.itonami.app.card-statement-test
    cloud.itonami.app.cli-test
    cloud.itonami.app.west-kotoba-refactor-test
    cloud.itonami.app.commands-test
    cloud.itonami.app.connectors-test
    cloud.itonami.app.desktop-test
    cloud.itonami.app.device-test
    cloud.itonami.app.decision-method-test
    cloud.itonami.app.disk-space-test
    cloud.itonami.app.appearance-test
    cloud.itonami.app.hokusai-test
    cloud.itonami.app.media-tools-test
    cloud.itonami.app.git-hygiene-test
    cloud.itonami.app.bot-test
    cloud.itonami.app.bot-slo-test
    cloud.itonami.app.bot-authority-test
    cloud.itonami.app.bot-dispatcher-test
    cloud.itonami.app.bot-identity-test
    cloud.itonami.app.bots-test
    cloud.itonami.app.virtual-shell-test
    cloud.itonami.app.host-grant-test
    cloud.itonami.app.host-store-bound-test
    cloud.itonami.app.store-journal-test
    cloud.itonami.app.loops-test
    cloud.itonami.app.lawfirm-test
    cloud.itonami.app.kotobase-federation-test
    cloud.itonami.app.local-query-test
    cloud.itonami.app.fax-test
    cloud.itonami.app.tenant-capability-test
    cloud.itonami.app.freebusy-test
    cloud.itonami.app.metrics-test
    cloud.itonami.app.portfolio-test
    cloud.itonami.app.policy-kotoba-parity-test
    cloud.itonami.app.native-canary-test
    cloud.itonami.app.health-kotoba-parity-test
    cloud.itonami.app.workforce-cadence-kotoba-parity-test
    cloud.itonami.app.health-http-test
    cloud.itonami.app.store-core-test
    cloud.itonami.app.store-core-kotoba-parity-test
    cloud.itonami.app.store-agreement-test
    cloud.itonami.app.central-auth-http-test
    cloud.itonami.app.oauth-resource-kotoba-parity-test
    cloud.itonami.app.oauth-resource-http-test
    cloud.itonami.app.did-web-kotoba-parity-test
    cloud.itonami.app.did-web-http-test
    cloud.itonami.app.trust-discovery-http-test
    cloud.itonami.app.humanity-trust-test
    cloud.itonami.app.humanity-trust-http-test
    cloud.itonami.app.human-work-test
    cloud.itonami.app.human-work-assurance-test
    cloud.itonami.app.human-work-http-test
    cloud.itonami.app.human-work-x402-test
    cloud.itonami.app.fleet-core-kotoba-parity-test
    cloud.itonami.app.organism-worker-kotoba-parity-test
    cloud.itonami.app.kotoba-oracle-test
    cloud.itonami.app.oracle-cljs-parity-test
    cloud.itonami.app.work-transitions-kotoba-parity-test
    cloud.itonami.app.approval-kotoba-parity-test
    cloud.itonami.app.routine-kotoba-parity-test
    cloud.itonami.app.model-routing-kotoba-parity-test
    cloud.itonami.app.bot-turn-guards-test
    cloud.itonami.app.model-routing-http-test
    cloud.itonami.app.routines-test
    cloud.itonami.app.handoff-kotoba-parity-test
    cloud.itonami.app.peer-kotoba-parity-test
    cloud.itonami.app.session-handoff-kotoba-parity-test
    cloud.itonami.app.mail-age-key-test
    cloud.itonami.app.mail-authentication-test
    cloud.itonami.app.mail-origins-test
    cloud.itonami.app.mail-projects-test
    cloud.itonami.app.conversation-context-test
    cloud.itonami.app.project-repository-test
    cloud.itonami.app.project-remote-test
    cloud.itonami.app.project-transfer-test
    cloud.itonami.app.repos-test
    cloud.itonami.app.repository-storage-test
    cloud.itonami.app.repository-qualification-test
    cloud.itonami.app.repository-invariants-test
    cloud.itonami.app.repository-runtime-test
    cloud.itonami.app.repository-actor-test
    cloud.itonami.app.repository-profile-ci-test
    cloud.itonami.app.authority.adapters-test
    cloud.itonami.app.authority.api-test
    cloud.itonami.app.authority.number-test
    cloud.itonami.app.authority.payment-test
    cloud.itonami.app.authority.posture-test
    cloud.itonami.app.authority-http-test
    cloud.itonami.app.authority.transport-test
    cloud.itonami.app.config-test
    cloud.itonami.app.contracts-test
    cloud.itonami.app.chronicle-test
    cloud.itonami.app.core-test
    cloud.itonami.app.credential-http-test
    cloud.itonami.app.credential-rdf-test
    cloud.itonami.app.presentation-request-test
    cloud.itonami.app.credential-sd-jwt-test
    cloud.itonami.app.credential-test
    cloud.itonami.app.credential-trust-test
    cloud.itonami.app.data-isolation-test
    cloud.itonami.app.did-test
    cloud.itonami.app.acme-test
    cloud.itonami.app.binding-sweep-test
    cloud.itonami.app.domain-name-test
    cloud.itonami.app.domain-binding-kotoba-parity-test
    cloud.itonami.app.domain-verification-test
    cloud.itonami.app.domain-verification-http-test
    cloud.itonami.app.email-login-test
    cloud.itonami.app.config-policy-test
    cloud.itonami.app.host-bounds-test
    cloud.itonami.app.provider-retry-test
    cloud.itonami.app.identity-lifecycle-test
    cloud.itonami.app.issue-comment-test
    cloud.itonami.app.lifecycle-test
    cloud.itonami.app.issue-comment-http-test
    cloud.itonami.app.loopback-origin-test
    cloud.itonami.app.sso-login-test
    cloud.itonami.app.documents-test
    cloud.itonami.app.drive-crypto-test
    cloud.itonami.app.drive-delivery-test
    cloud.itonami.app.file-provider-test
    cloud.itonami.app.file-provider-http-test
    cloud.itonami.app.email-login-test
    cloud.itonami.app.workspace-reachability-test
    cloud.itonami.app.workspace-tools-test
    cloud.itonami.app.web-script-test
    cloud.itonami.app.bundle-test
    cloud.itonami.app.kotobase-objects-test
    cloud.itonami.app.drive-store-migration-test
    cloud.itonami.app.drive-fs-test
    cloud.itonami.app.latest-test
    cloud.itonami.app.graph-test
    cloud.itonami.app.work-governance-test
    cloud.itonami.app.github-projects-writeback-test
    cloud.itonami.app.github-projects-source-test
    cloud.itonami.app.work-runtime-test
    cloud.itonami.app.work-partition-store-test
    cloud.itonami.app.work-approval-test
    cloud.itonami.app.work-organism-dispatch-test
    cloud.itonami.app.esign-test
    cloud.itonami.app.esign-retention-test
    cloud.itonami.app.filecoin-test
    cloud.itonami.app.fleet-test
    cloud.itonami.app.folder-sync-test
    cloud.itonami.app.gc-test
    cloud.itonami.app.operator-test
    cloud.itonami.app.funding-test
    cloud.itonami.app.mcp-test
    cloud.itonami.app.mcp-http-test
    cloud.itonami.app.namespaces-test
    cloud.itonami.app.fleet-tools-test
    cloud.itonami.app.openai-compat-test
    cloud.itonami.app.hermes-compat-test
    cloud.itonami.app.hermes-migration-test
    cloud.itonami.app.hermes-compat-http-test
    cloud.itonami.app.provider-test
    cloud.itonami.app.pageview-test
    cloud.itonami.app.passkey-test
    cloud.itonami.app.payment-settlement-actor-test
    cloud.itonami.app.mailbox-test
    cloud.itonami.app.mailbox-http-test
    cloud.itonami.app.mail-sync-test
    cloud.itonami.app.mail-account-test
    cloud.itonami.app.mail-domain-authority-test
    cloud.itonami.app.mail-domain-records-test
    cloud.itonami.app.tls-binding-test
    cloud.itonami.app.tls-certificate-test
    cloud.itonami.app.mail-gmail-test
    cloud.itonami.app.mail-imap-test
    cloud.itonami.app.mail-pop3-test
    cloud.itonami.app.mail-send-test
    cloud.itonami.app.messenger-test
    cloud.itonami.app.messenger-http-test
    cloud.itonami.app.organism-messenger-transport-test
    cloud.itonami.app.signal-browser-test
    cloud.itonami.app.scheduler-test
    cloud.itonami.app.scheduler-http-test
    cloud.itonami.app.bulky-waste-test
    cloud.itonami.app.bulky-waste-http-test
    cloud.itonami.app.sites-test
    cloud.itonami.app.payment-tools-test
    cloud.itonami.app.paypay-bank-test
    cloud.itonami.app.storj-node-test
    cloud.itonami.app.store-test
    cloud.itonami.app.storj-test
    cloud.itonami.app.tenant-connection-test
    cloud.itonami.app.tenant-connection-http-test
    cloud.itonami.app.tenant-repository-test
    cloud.itonami.app.updater-test
    cloud.itonami.app.oauth-resource-test
    cloud.itonami.app.org-root-did-test
    cloud.itonami.app.domain-tools-test
    cloud.itonami.app.bot-import-test
    cloud.itonami.app.did-webvh-http-test
    cloud.itonami.app.oauth-did-binding-test
    cloud.itonami.app.worker-http-test
    cloud.itonami.app.wallet-test
    cloud.itonami.app.smart-account-owner-test
    cloud.itonami.app.wallet-http-test
    cloud.itonami.app.wallet-send-test
    cloud.itonami.app.commerce-test
    cloud.itonami.app.storefront-http-test])

(defn- test-namespaces-on-disk
  "Every `*_test.clj` under test/, as the namespace symbol it declares."
  []
  (->> (file-seq (io/file "test"))
       (filter #(.isFile ^java.io.File %))
       (map #(.getPath ^java.io.File %))
       (filter #(str/ends-with? % "_test.clj"))
       (map #(-> %
                 (str/replace #"^test/" "")
                 (str/replace #"\.clj$" "")
                 (str/replace "_" "-")
                 (str/replace "/" ".")
                 symbol))
       set))

(defn- unlisted []
  (let [on-disk (test-namespaces-on-disk)]
    ;; only meaningful when run from the project root, where test/ exists
    (when (seq on-disk)
      (sort (remove (set namespaces) on-disk)))))

(defn -main [& _]
  (when-let [missing (seq (unlisted))]
    (println "test-runner: these test namespaces exist but are not in the list:")
    (doseq [n missing] (println "  " n))
    (println "Add them to cloud.itonami.app.test-runner, or they do not run.")
    (System/exit 1))
  (let [{:keys [fail error]}
        (binding [store/*reload-before-transaction?* false]
          (apply test/run-tests namespaces))]
    (System/exit (if (zero? (+ fail error)) 0 1))))
