(ns cloud.itonami.app.canvas
  "The lean canvas of one business, and proposals to change it.

  Phase 2 of ADR-2607309600. The read side is the folded canvas; the write side
  is a proposal, and the difference between them is the whole namespace.

  ## Reading: the fold happens once, upstream

  `90-docs/business/<product>-canvas.datoms.edn` is the FOLDED canvas — the base
  datoms with every canvas-ledger event applied — generated by `gftd canvas
  datoms` in the superproject. This namespace reads that projection and does not
  fold anything.

  That is deliberate. `gftd.canvas/apply-event` is the fold, and a second
  implementation of it here would drift: the rolling-observation window alone
  (three most recent `観測 (signal):` items per block, so a routine's hourly
  append does not bury the Problem block) is behaviour nobody would reproduce by
  reading the ledger format. The app is released on its own and cannot depend on
  that tool, so the tool emits data and the app consumes it.

  It also means the app cannot see anything the projection does not carry, and it
  says so rather than guessing: `:missing` names the file it looked for.

  ## Writing: an app proposal is not a ledger entry

  `canvas-ledger.edn` is append-only and governed — every event goes through
  `gftd.react/governor`, which can reject it. This app has no governor and no
  business writing to that file, so `propose!` records the proposal in the app's
  own store and renders the exact `gftd` command that would apply it. Nothing
  here appends to the ledger. `writes-only-locally?` states that surface and a
  test holds it, the same way `business/binds-only-locally?` does.

  ## A landed proposal is measured, not asserted

  A proposal's state is not a field somebody sets. `:awaiting-governor` means the
  value is not in the projection; `:landed` means it IS — read back out of the
  regenerated projection, which is only true after the governor accepted it and
  the projection was rebuilt. With no workspace to read, the state is
  `:unverifiable`, which is neither of the other two.

  This is the same rule `operator/register-endpoint!` applies by probing an
  endpoint instead of trusting a claim, and `funding` applies by refusing an
  unknown balance instead of reading it as zero."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [cloud.itonami.app.business :as business]
            [cloud.itonami.app.store :as store])
  (:import [java.util UUID]))

(def schema "cloud.itonami.app.canvas.v1")

(def actions
  "What a proposal may ask for. Exactly the three canvas mutations the ledger
  understands (`gftd canvas add|retract|note`) — the app does not invent a fourth
  kind of change that the governor would have no rule for."
  #{:canvas/add-item :canvas/retract-item :canvas/note})

(def ledger-authority
  "Shown beside every proposal. The app is not the governor and says so."
  (str "このアプリは canvas-ledger に書きません。"
       "提案は governor を通してから ledger に入ります。"))

(defn- refuse [type detail] (throw (ex-info detail {:type type})))

(defn- projection-path [product]
  (str "90-docs/business/" (name product) "-canvas.datoms.edn"))

;; ---------------------------------------------------------------------------
;; read
;; ---------------------------------------------------------------------------

(def ^:private unreadable ::unreadable)

(defn- read-projection [ws product]
  (when-let [root (:file ws)]
    (let [f (io/file root (projection-path product))]
      (when (.isFile f)
        (try (edn/read-string (slurp f))
             (catch Exception _ unreadable))))))

;; The projection's datoms are NOT passed through to the client. Namespaces are
;; dropped on the wire (`clojure.data.json` writes `:canvas/id` as `id`), and the
;; datoms have three pairs that collide once stripped:
;;
;;   :db/id     + :canvas/id  -> id
;;   :hyp/status + :gate/status -> status
;;   :hyp/evidence + :gate/evidence -> evidence
;;
;; A colliding pair does not error — one silently wins, by map iteration order —
;; and the two `status` values are exactly the pair this view exists to show
;; separately: what the ledger says about a hypothesis versus what the metrics
;; say. So the shape is re-keyed here, explicitly, and a test asserts that no two
;; keys in it strip to the same name.

(defn- kw->str
  "A keyword as its full name, namespace included.

  Keyword VALUES lose their namespace on the wire the same way keys do, so
  `:hyp/t1` would arrive as `t1` and `:lean/problem` as `problem`. The ids are
  what a proposal names and what a reader copies into a `gftd` command, so they
  travel as strings that survive intact."
  [k]
  (when k (str (symbol k))))

(defn- block->wire [b]
  (cond-> {:id (kw->str (:canvas/id b))
           :block (kw->str (:canvas/block b))
           :label (:canvas/label b)
           :order (:canvas/order b)
           :items (vec (:canvas/items b))}
    (:canvas/note b) (assoc :note (:canvas/note b))))

(defn- hyp->wire [h]
  (cond-> {:id (kw->str (:hyp/id h))
           :claim (:hyp/claim h)
           :gate (:hyp/gate h)
           :risk (:hyp/risk h)
           :status (:hyp/status h)}
    (:hyp/evidence h) (assoc :evidence (:hyp/evidence h))
    (:gate/status h) (assoc :gate-status (:gate/status h))
    (:gate/distance h) (assoc :gate-distance (:gate/distance h))
    (:gate/evidence h) (assoc :gate-evidence (:gate/evidence h))
    (seq (:gate/needs h)) (assoc :gate-needs (vec (:gate/needs h)))))

(defn- proposal->wire [p state]
  {:id (:proposal/id p)
   :business-id (:proposal/business-id p)
   :action (:proposal/action p)
   :canvas-id (:proposal/canvas-id p)
   :value (:proposal/value p)
   :reason (:proposal/reason p)
   :proposed-by (:proposal/proposed-by p)
   :proposed-at (:proposal/proposed-at p)
   :withdrawn-by (:proposal/withdrawn-by p)
   :withdrawn-at (:proposal/withdrawn-at p)
   :state state})

(defn- riskiest
  "The hypothesis the canvas itself marks as riskiest, or nil.

  Not 'the first one' and not a guess: `:hyp/risk :riskiest` is a field the
  portfolio datoms carry, and a canvas that never marked one gets no highlight
  rather than an arbitrary block lit up."
  [hyps]
  (first (filter #(= :riskiest (:hyp/risk %)) hyps)))

(defn canvas
  "The folded canvas of `b`, or the reason there is none.

  `:state` mirrors the face states in `business`: `:unbound` (this business has
  no `:canvas/product`), `:unresolvable` (it has one, but no workspace checkout
  to read), `:missing` (checkout, no projection for that product), `:unreadable`
  (projection would not parse) or `:resolved`."
  [configuration b]
  (let [ws (business/workspace configuration)
        product (:business/canvas b)
        path (some-> product projection-path)]
    (cond
      (nil? product)
      {:schema schema :state :unbound
       :detail "この事業には canvas が紐付いていません"}

      (not= :present (:state ws))
      {:schema schema :state :unresolvable :product product :source path
       :detail (:detail ws)}

      :else
      (let [tx (read-projection ws product)]
        (cond
          (nil? tx)
          {:schema schema :state :missing :product product :source path
           :detail (str path " が workspace にありません。"
                        "superproject で `gftd canvas datoms --all` を実行すると生成されます")}

          (identical? unreadable tx)
          {:schema schema :state :unreadable :product product :source path
           :detail (str path " を読めませんでした")}

          :else
          (let [entities (filter map? tx)
                header (first (filter :projection/id entities))
                blocks (->> entities (filter :canvas/block) (sort-by :canvas/order)
                            (mapv block->wire))
                raw-hyps (->> entities (filter :hyp/id) (sort-by :hyp/id) vec)
                hyps (mapv hyp->wire raw-hyps)
                risk (riskiest raw-hyps)]
            {:schema schema :state :resolved :product product :source path
             :as-of (:projection/as-of header)
             :layer (:projection/layer header)
             :projection-source (:projection/source header)
             :blocks blocks
             :hypotheses hyps
             :riskiest-hyp (kw->str (:hyp/id risk))
             ;; The block the riskiest hypothesis is about is not derivable from
             ;; the datoms — no attribute links a hypothesis to a block — so it
             ;; is absent rather than inferred from wording.
             :riskiest-block nil
             ;; Reported, not silently trusted: the header states how many
             ;; entities the generator emitted, and a projection whose file was
             ;; truncated would disagree with it.
             :counts {:blocks (count blocks)
                      :hypotheses (count hyps)
                      :declared-blocks (:projection/blocks header)
                      :declared-hypotheses (:projection/hypotheses header)
                      :complete? (and (= (count blocks) (:projection/blocks header))
                                      (= (count hyps) (:projection/hypotheses header)))}}))))))

;; ---------------------------------------------------------------------------
;; proposals (recorded locally; the ledger is somebody else's authority)
;; ---------------------------------------------------------------------------

(defn- proposal-path [id] [:canvas-proposals id])

(defn gftd-command
  "The command that would apply this proposal, for a human or a governor run to
  copy. Rendering it is the honest alternative to an Apply button the app cannot
  back: the app knows exactly what it is asking for and does not pretend it can
  do it."
  [{:keys [proposal/action proposal/canvas-id proposal/value]}]
  (let [verb (case action
               :canvas/add-item "add"
               :canvas/retract-item "retract"
               :canvas/note "note")]
    (str "nbb 70-tools/bmc/bin/gftd.cljs canvas " verb
         " " canvas-id " " (pr-str value))))

(defn proposals
  "Every canvas proposal for this session's organization, newest first."
  [session]
  (->> (vals (get-in (store/snapshot) [:canvas-proposals] {}))
       (filter #(= (:organization-id session) (:organization-id %)))
       (sort-by :proposal/proposed-at)
       reverse
       vec))

(defn- item-present?
  "Whether the projection already carries what a proposal asked for. This is the
  only evidence the app has that a proposal landed."
  [c {:keys [proposal/action proposal/canvas-id proposal/value]}]
  (when (= :resolved (:state c))
    ;; Both sides are strings here: the proposal's canvas-id came from a form
    ;; field, and `block->wire` already stringified the projection's keyword.
    (let [block (first (filter #(= canvas-id (:id %)) (:blocks c)))]
      (case action
        :canvas/add-item (boolean (some #{value} (:items block)))
        ;; A retraction has landed when the item is gone — but only if the block
        ;; itself was found. An absent block would make every retraction read as
        ;; landed, which is the difference between 「消えた」 and 「見ていない」.
        :canvas/retract-item (and (some? block) (not (some #{value} (:items block))))
        :canvas/note (= value (:note block))))))

(defn proposal-state
  "Derived, never stored.

  `:withdrawn` is the one state a human sets, because 「もう要らない」 is not
  something the projection can show. Everything else is read back out of the
  projection: an app that stored `:landed` would be recording its own hope."
  [c proposal]
  (cond
    (:proposal/withdrawn-at proposal) :withdrawn
    (not= :resolved (:state c)) :unverifiable
    (item-present? c proposal) :landed
    :else :awaiting-governor))

(defn snapshot
  "The canvas read model for one business, with its proposals and their derived
  states."
  [configuration session business-id]
  (let [b (business/business session business-id)]
    (when b
      (let [c (canvas configuration b)
            ps (filterv #(= business-id (:proposal/business-id %)) (proposals session))]
        {:schema schema
         :business (select-keys b [:business/id :business/slug :business/name
                                   :business/canvas])
         :canvas c
         :authority ledger-authority
         :proposals (mapv (fn [p]
                            (let [st (proposal-state c p)]
                              (cond-> (proposal->wire p st)
                                ;; No command for something already landed or
                                ;; withdrawn: offering one invites re-applying an
                                ;; append-only event a second time.
                                (contains? #{:awaiting-governor :unverifiable} st)
                                (assoc :command (gftd-command p)))))
                          ps)}))))

(defn propose!
  "Record a proposal to change this business's canvas.

  Validated against the ledger's vocabulary, not against the projection: a
  proposal for a block the checkout does not have is still a real proposal, and
  refusing it would make the app unusable in the released install that has no
  checkout — the same reason `business/bind!` records an unconfirmable binding."
  [session business-id {:keys [action canvas-id value reason by]}]
  (let [b (business/business session business-id)
        action (some-> action str (str/replace #"^:" "") keyword
                       (as-> k (if (namespace k) k (keyword "canvas" (name k)))))]
    (when-not b
      (refuse :business/not-found "この organization に該当する business がありません"))
    (when-not (contains? actions action)
      (refuse :canvas/action-unsupported
              (str "action は " (str/join " / " (sort (map str actions))) " のいずれかです")))
    (when-not (:business/canvas b)
      (refuse :canvas/product-unbound
              "先に事業へ canvas (:canvas/product) を紐付けてください"))
    (let [canvas-id (some-> canvas-id str str/trim not-empty)
          value (some-> value str str/trim not-empty)]
      (when-not canvas-id
        (refuse :canvas/canvas-id-missing "canvas-id が必要です（例 cloud-itonami.problem）"))
      ;; :canvas/note replaces a note and :canvas/retract-item names the item to
      ;; remove, so all three actions carry a value. An empty one would record a
      ;; proposal that asks for nothing.
      (when-not value
        (refuse :canvas/value-missing "提案の内容が必要です"))
      (when-not (seq (str by))
        (refuse :canvas/anonymous-proposal
                "提案には提案者が必要です（誰の判断かが残らない提案は提案ではありません）"))
      (let [id (str "canvas-proposal-" (UUID/randomUUID))
            record {:schema schema
                    :proposal/id id
                    :proposal/business-id business-id
                    :organization-id (:organization-id b)
                    :proposal/product (:business/canvas b)
                    :proposal/action action
                    :proposal/canvas-id canvas-id
                    :proposal/value value
                    :proposal/reason (some-> reason str str/trim not-empty)
                    :proposal/proposed-by (str by)
                    :proposal/proposed-at (store/now)}]
        (store/transact! assoc-in (proposal-path id) record)
        record))))

(defn withdraw!
  "Record that a human dropped this proposal. The record is kept: a proposal that
  was raised and abandoned is a different fact from one that was never made, and
  the fleet's ledgers keep holds as well as commits for the same reason."
  [session proposal-id {:keys [by]}]
  (let [p (get-in (store/snapshot) (proposal-path proposal-id))]
    (when-not (and p (= (:organization-id session) (:organization-id p)))
      (refuse :canvas/proposal-not-found "該当する提案がありません"))
    (let [p' (assoc p :proposal/withdrawn-at (store/now)
                    :proposal/withdrawn-by (str by))]
      (store/transact! assoc-in (proposal-path proposal-id) p')
      p')))

(defn counts
  "How many proposals are still waiting, for the nav badge. Only what the
  projection could not account for — a landed proposal is finished work and
  padding the badge with it would make the number stop meaning anything."
  [configuration session]
  (let [ps (proposals session)
        states (map (fn [p]
                      (let [b (business/business session (:proposal/business-id p))]
                        (proposal-state (if b (canvas configuration b) {:state :unbound}) p)))
                    ps)
        f (frequencies states)]
    {:proposals (count ps)
     :awaiting (get f :awaiting-governor 0)
     :landed (get f :landed 0)
     :unverifiable (get f :unverifiable 0)
     :withdrawn (get f :withdrawn 0)}))

(defn writes-only-locally?
  "Every store path this namespace writes. The canvas ledger is not among them
  and a test asserts this vector, so adding a ledger write has to change it."
  []
  [[:canvas-proposals]])
