(ns cloud.itonami.app.fleet
  "The cloud-itonami actor fleet, as a directory the app can search.

  1,183 actors carry a `blueprint.edn` describing what they are — domain,
  governor, maturity, ISIC/ISCO/ISO-3166 coding, social impact. Seven of them
  also say where they are. That gap is the whole shape of this namespace.

  A blueprint had no address field at all until 2026-07-30: not an endpoint, a
  URL, an XRPC surface or a DID, anywhere in the fleet. So the fleet could not
  be integrated by calling it — there was nothing to call. What it can support
  is a directory: what exists, in what sector, at what maturity.

  `:endpoint` was then added to the actors that are actually deployed and
  answering. Those are callable. Everything else is a directory record, and
  `callable?` is the line between them. The catalog never guesses an address:
  an actor with a `wrangler.jsonc` but no deployment gets no endpoint, because
  a plausible-looking URL that answers nothing is worse than an absent one.

  Health is measured, never assumed, and an unreachable probe is `:unknown`
  rather than `false` — the same discipline `account-services` applies to
  usage meters, and for the same reason: a failed measurement is not a
  measurement of failure. The probe path is declared by the actor, never
  guessed: the Workers answer /health with JSON, while the Pages actors answer
  /health with 200 and their SPA index, so an assumed path would read HTML as
  a healthy API.

  `:id` is not unique. Three repositories declare an id another already owns,
  so lookup is by `:repo` — the directory, which is unique — and `find-by-id`
  returns every match rather than picking one.

  `:execution` says when an actor runs. An `:on-demand` actor wakes for an API
  or MCP call and stops; no endpoint means nobody has exposed it yet, which is
  unremarkable when most have no deploy config at all. A `:resident` actor —
  the loop orchestrators and the person organisms — carries its own loop and
  runs unprompted.

  An earlier version of this docstring said a resident actor without an
  endpoint means its loop is dead. That was wrong, and worth correcting rather
  than quietly dropping: a `loop-*` orchestrator runs in CI or on a schedule
  and has no HTTP surface by design, so its endpoint was never going to exist.
  Liveness for a resident actor is whether it recently recorded evidence — the
  taxonomy makes `:record-evidence` one of its obligations — and this catalog
  does not carry that. It reports `:not-probeable` and says why, instead of
  reusing a signal that does not apply.

  Some entries are `:reference-only`. They are in the catalog because west
  pins them and the authority classifies them, not because they carry a
  blueprint: repository, remote and revision, and nothing read out of the
  repository itself. That is how the resident actors got here without every
  one of them having to grow a blueprint.edn.

  The value is derived from the workspace authority
  (`manifest/repository-rules.edn`, ADR-2607299000), not restated in the app,
  and it is absent where that vocabulary does not yet reach."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(def schema "cloud.itonami.fleet-catalog.v1")

(def ^:private resource-name "itonami-fleet-catalog.edn")

(defn- read-catalog []
  (if-some [r (io/resource resource-name)]
    (let [c (edn/read-string (slurp r))]
      (when-not (= schema (:schema c))
        (throw (ex-info "fleet catalog schema mismatch"
                        {:type :fleet/schema-mismatch
                         :expected schema :found (:schema c)})))
      c)
    (throw (ex-info (str "fleet catalog resource missing: " resource-name)
                    {:type :fleet/catalog-missing}))))

(def catalog
  "Parsed catalog. Generated by scripts/gen-itonami-fleet-catalog.cljs in the
  superproject and shipped as a resource — cloud-itonami-app is released on its
  own and cannot assume a west checkout of the fleet exists beside it."
  (delay (read-catalog)))

(defn actors [] (:actors @catalog))

(defn callable?
  "True when this actor declares an address. Absent means not deployed, or
  deployed with no route — not 'unknown, try it and see'."
  [actor]
  (some? (:endpoint actor)))

(defn probeable?
  "True when the actor names a health path. A callable actor need not be
  probeable: the Pages actors serve a real API under /api/* and have no health
  endpoint at all, so there is nothing honest to probe.

  Resident actors are never probeable through this namespace. A loop that runs
  on a schedule has no HTTP surface to ask, and asking the wrong question would
  be worse than not asking."
  [actor]
  (and (callable? actor) (some? (:health-path actor))))

(defn callable [] (filterv callable? (actors)))

(defn actor
  "Look up by repository directory, which is unique. Prefer this over
  find-by-id: :id collides for three actors and cannot resolve them."
  [repo]
  (first (filter #(= repo (:repo %)) (actors))))

(defn find-by-id
  "Every actor declaring this id — usually one, occasionally two. Returns a
  vector rather than a single record because returning the first match would
  make a collision look like a clean answer."
  [id]
  (filterv #(= id (:id %)) (actors)))

(defn duplicate-ids
  "Ids claimed by more than one repository. Non-empty today: three actors were
  duplicated into a second repo (a -component, a -codex, and an isic code
  written both zero-padded and not), and each copy kept the original's id.
  Which copy is canonical is not something this catalog can decide."
  []
  (:duplicate-ids @catalog))

(defn by-execution
  "Actors with this execution model. `:unclassified` for the families the
  authority's prefix rules do not yet cover — marketplace, assoc, municipality
  and others. That is a gap in the vocabulary, not a property of the actors,
  and it is left visible rather than defaulted to a plausible value."
  [execution]
  (if (= :unclassified execution)
    (filterv #(nil? (:execution %)) (actors))
    (filterv #(= execution (:execution %)) (actors))))

(defn reference-only
  "Entries present as a pin rather than a description: repo, remote, revision.
  No file was read from them."
  []
  (filterv :reference-only (actors)))

(defn revision
  "The west pin for this actor — the hash the workspace currently agrees on."
  [actor]
  (:revision actor))

(defn pin-age-days
  "Days since the pinned commit was authored, or nil if no date was recorded.

  This measures the PIN, not the actor. It is the closest thing this catalog
  has to liveness for a resident actor, and it is not liveness: a loop- repo
  does commit what it produces — loop-system-dynamics carries evidence/ and
  ledger/ and writes to them — so a pin that has not moved in months means
  either the loop stopped or nobody advanced the pin. Both deserve a look and
  this cannot tell them apart.

  Recorded only for :reference-only entries, which is where every resident
  actor is; fetching it for all 1,208 would mean 1,208 API calls at generation."
  [actor]
  (when-some [t (:revision-committed-at actor)]
    (-> (java.time.Duration/between (java.time.Instant/parse t) (java.time.Instant/now))
        .toDays)))

(defn stale-pins
  "Actors whose pin has not moved in `days`, oldest first. Resident actors are
  the interesting case — an orchestrator that has not committed evidence in a
  month is either stopped or unpinned — but the query is not restricted to
  them, because an on-demand actor with a very old pin is worth noticing too."
  ([] (stale-pins 30))
  ([days]
   (->> (actors)
        (keep (fn [a] (when-some [age (pin-age-days a)]
                        (when (>= age days) (assoc a :pin-age-days age)))))
        (sort-by :pin-age-days >)
        vec)))

(defn counts
  "Directory shape at a glance. `:company-records` are the 155 repositories
  whose blueprint.edn is a `:company/*` legal-entity record rather than an
  actor — they belong to the cloud-itonami-lei dataset and are counted here
  only so this total can be reconciled against the repository count."
  []
  (let [c @catalog]
    {:actors (:count c)
     :callable (:callable-count c)
     :company-records (:company-record-count c)
     :duplicate-ids (count (:duplicate-ids c))
     :reference-only (count (filter :reference-only (:actors c)))
     :by-execution (frequencies (map #(or (:execution %) :unclassified)
                                     (:actors c)))}))

;; ── search ───────────────────────────────────────────────────────────

(defn- matches-text? [actor q]
  (let [q (str/lower-case q)]
    (some (fn [v] (and v (str/includes? (str/lower-case (str v)) q)))
          [(:id actor) (:name actor) (:domain actor)])))

(defn- isic-of [actor]
  (or (:isic actor) (:isic-rev5 actor) (:isic-rev4 actor)))

(defn search
  "Filter the directory. All criteria are ANDed; omitted criteria do not
  constrain. `:isic` matches whichever revision an actor happens to code in —
  the fleet uses :isic, :isic-rev4 and :isic-rev5 inconsistently, and making a
  caller know which would leak that inconsistency into every query.

    (search {:domain :marketplace/order-orchestration})
    (search {:iso3166 \"JPN\" :maturity :implemented})
    (search {:text \"marketplace\" :callable? true})"
  [{:keys [text domain governor maturity status isic iso3166]
    want-callable :callable?}]
  (cond->> (actors)
    text      (filter #(matches-text? % text))
    domain    (filter #(= domain (:domain %)))
    governor  (filter #(= governor (:governor %)))
    maturity  (filter #(= maturity (:maturity %)))
    status    (filter #(= status (:status %)))
    isic      (filter #(= isic (isic-of %)))
    iso3166   (filter #(= iso3166 (:iso3166 %)))
    ;; bound as want-callable so the criterion does not shadow callable?
    (some? want-callable) (filter #(= (boolean want-callable) (callable? %)))
    true      vec))

(defn facets
  "Value → count for one field, most common first. Drives the directory's
  filter UI without hardcoding a list that would drift from the fleet."
  [field]
  (->> (actors)
       (keep field)
       frequencies
       (sort-by (juxt (comp - val) (comp str key)))
       vec))

;; ── health ───────────────────────────────────────────────────────────

(defn- probe*
  "GET {endpoint}{health-path}. Returns :up, :down or :unknown.

  :down means the actor answered and said it was unwell. :unknown means we
  could not find out — timeout, DNS, TLS. Collapsing those two would report a
  network problem as a broken actor."
  [endpoint health-path timeout-ms]
  (try
    (let [c (doto ^java.net.HttpURLConnection
                  (.openConnection (java.net.URL. (str endpoint health-path)))
              (.setRequestMethod "GET")
              (.setConnectTimeout timeout-ms)
              (.setReadTimeout timeout-ms))
          code (.getResponseCode c)]
      (.disconnect c)
      (if (<= 200 code 299) :up :down))
    (catch java.io.IOException _ :unknown)
    (catch java.net.URISyntaxException _ :unknown)))

(defn probe-health!
  "Probe every callable actor. Returns {repo {:endpoint ... :health ...}}.

  Keyed by repo, not id, because id collides. An actor that declares no health
  path reports :not-probeable — it is reachable, it just offers nothing to ask.
  Calling that :up would be a guess and calling it :down would be a smear.

  Not called on load: the directory is useful offline, and 1,183 records should
  not wait on network round-trips to be listed."
  ([] (probe-health! 3000))
  ([timeout-ms]
   (into {}
         (map (fn [a]
                [(:repo a)
                 {:endpoint (:endpoint a)
                  :endpoint-kind (:endpoint-kind a)
                  :health (if (probeable? a)
                            (probe* (:endpoint a) (:health-path a) timeout-ms)
                            :not-probeable)}]))
         (callable))))
